const Nebraska = [
  {
    "rowId": 22,
    "orderId": "CA-2016-137330",
    "orderDate": "12/9/16",
    "shipDate": "12/13/16",
    "shipMode": "Standard Class",
    "customerId": "KB-16585",
    "customerName": "Ken Black",
    "segment": "Corporate",
    "country": "United States",
    "city": "Fremont",
    "state": "Nebraska",
    "postalCode": 68025,
    "region": "Central",
    "productId": "OFF-AR-10000246",
    "category": "Office Supplies",
    "subCategory": "Art",
    "productName": "Newell 318",
    "sales": 19.46,
    "quantity": 7,
    "discount": 0,
    "profit": 5.0596
  },
  {
    "rowId": 23,
    "orderId": "CA-2016-137330",
    "orderDate": "12/9/16",
    "shipDate": "12/13/16",
    "shipMode": "Standard Class",
    "customerId": "KB-16585",
    "customerName": "Ken Black",
    "segment": "Corporate",
    "country": "United States",
    "city": "Fremont",
    "state": "Nebraska",
    "postalCode": 68025,
    "region": "Central",
    "productId": "OFF-AP-10001492",
    "category": "Office Supplies",
    "subCategory": "Appliances",
    "productName": "Acco Six-Outlet Power Strip, 4' Cord Length",
    "sales": 60.34,
    "quantity": 7,
    "discount": 0,
    "profit": 15.6884
  },
  {
    "rowId": 808,
    "orderId": "CA-2015-140921",
    "orderDate": "2/3/15",
    "shipDate": "2/5/15",
    "shipMode": "First Class",
    "customerId": "AA-10375",
    "customerName": "Allen Armold",
    "segment": "Consumer",
    "country": "United States",
    "city": "Omaha",
    "state": "Nebraska",
    "postalCode": 68104,
    "region": "Central",
    "productId": "FUR-FU-10003347",
    "category": "Furniture",
    "subCategory": "Furnishings",
    "productName": "Coloredge Poster Frame",
    "sales": 28.4,
    "quantity": 2,
    "discount": 0,
    "profit": 11.076
  },
  {
    "rowId": 809,
    "orderId": "CA-2015-140921",
    "orderDate": "2/3/15",
    "shipDate": "2/5/15",
    "shipMode": "First Class",
    "customerId": "AA-10375",
    "customerName": "Allen Armold",
    "segment": "Consumer",
    "country": "United States",
    "city": "Omaha",
    "state": "Nebraska",
    "postalCode": 68104,
    "region": "Central",
    "productId": "TEC-AC-10004901",
    "category": "Technology",
    "subCategory": "Accessories",
    "productName": "Kensington SlimBlade Notebook Wireless Mouse with Nano Receiver",
    "sales": 149.97,
    "quantity": 3,
    "discount": 0,
    "profit": 50.9898
  },
  {
    "rowId": 1509,
    "orderId": "CA-2017-108294",
    "orderDate": "12/10/17",
    "shipDate": "12/10/17",
    "shipMode": "Same Day",
    "customerId": "LS-16975",
    "customerName": "Lindsay Shagiari",
    "segment": "Home Office",
    "country": "United States",
    "city": "Omaha",
    "state": "Nebraska",
    "postalCode": 68104,
    "region": "Central",
    "productId": "OFF-BI-10004965",
    "category": "Office Supplies",
    "subCategory": "Binders",
    "productName": "Ibico Covers for Plastic or Wire Binding Elements",
    "sales": 34.5,
    "quantity": 3,
    "discount": 0,
    "profit": 15.525
  },
  {
    "rowId": 2791,
    "orderId": "CA-2014-125514",
    "orderDate": "9/21/14",
    "shipDate": "9/22/14",
    "shipMode": "First Class",
    "customerId": "BM-11650",
    "customerName": "Brian Moss",
    "segment": "Corporate",
    "country": "United States",
    "city": "Omaha",
    "state": "Nebraska",
    "postalCode": 68104,
    "region": "Central",
    "productId": "OFF-AP-10000358",
    "category": "Office Supplies",
    "subCategory": "Appliances",
    "productName": "Fellowes Basic Home/Office Series Surge Protectors",
    "sales": 25.96,
    "quantity": 2,
    "discount": 0,
    "profit": 7.5284
  },
  {
    "rowId": 2792,
    "orderId": "CA-2014-125514",
    "orderDate": "9/21/14",
    "shipDate": "9/22/14",
    "shipMode": "First Class",
    "customerId": "BM-11650",
    "customerName": "Brian Moss",
    "segment": "Corporate",
    "country": "United States",
    "city": "Omaha",
    "state": "Nebraska",
    "postalCode": 68104,
    "region": "Central",
    "productId": "OFF-AP-10003281",
    "category": "Office Supplies",
    "subCategory": "Appliances",
    "productName": "Acco 6 Outlet Guardian Standard Surge Suppressor",
    "sales": 36.27,
    "quantity": 3,
    "discount": 0,
    "profit": 10.881
  },
  {
    "rowId": 2793,
    "orderId": "CA-2014-125514",
    "orderDate": "9/21/14",
    "shipDate": "9/22/14",
    "shipMode": "First Class",
    "customerId": "BM-11650",
    "customerName": "Brian Moss",
    "segment": "Corporate",
    "country": "United States",
    "city": "Omaha",
    "state": "Nebraska",
    "postalCode": 68104,
    "region": "Central",
    "productId": "OFF-PA-10000029",
    "category": "Office Supplies",
    "subCategory": "Paper",
    "productName": "Xerox 224",
    "sales": 6.48,
    "quantity": 1,
    "discount": 0,
    "profit": 3.1104
  },
  {
    "rowId": 3582,
    "orderId": "CA-2017-117807",
    "orderDate": "10/1/17",
    "shipDate": "10/7/17",
    "shipMode": "Standard Class",
    "customerId": "DK-13090",
    "customerName": "Dave Kipp",
    "segment": "Consumer",
    "country": "United States",
    "city": "Fremont",
    "state": "Nebraska",
    "postalCode": 68025,
    "region": "Central",
    "productId": "OFF-PA-10000994",
    "category": "Office Supplies",
    "subCategory": "Paper",
    "productName": "Xerox 1915",
    "sales": 104.85,
    "quantity": 1,
    "discount": 0,
    "profit": 50.328
  },
  {
    "rowId": 3717,
    "orderId": "CA-2017-144568",
    "orderDate": "5/29/17",
    "shipDate": "6/2/17",
    "shipMode": "Standard Class",
    "customerId": "JO-15550",
    "customerName": "Jesus Ocampo",
    "segment": "Home Office",
    "country": "United States",
    "city": "Omaha",
    "state": "Nebraska",
    "postalCode": 68104,
    "region": "Central",
    "productId": "OFF-FA-10004395",
    "category": "Office Supplies",
    "subCategory": "Fasteners",
    "productName": "Plymouth Boxed Rubber Bands by Plymouth",
    "sales": 23.55,
    "quantity": 5,
    "discount": 0,
    "profit": 1.1775
  },
  {
    "rowId": 3790,
    "orderId": "US-2016-133508",
    "orderDate": "4/17/16",
    "shipDate": "4/21/16",
    "shipMode": "Standard Class",
    "customerId": "SW-20350",
    "customerName": "Sean Wendt",
    "segment": "Home Office",
    "country": "United States",
    "city": "Omaha",
    "state": "Nebraska",
    "postalCode": 68104,
    "region": "Central",
    "productId": "OFF-FA-10000134",
    "category": "Office Supplies",
    "subCategory": "Fasteners",
    "productName": "Advantus Push Pins, Aluminum Head",
    "sales": 29.05,
    "quantity": 5,
    "discount": 0,
    "profit": 9.0055
  },
  {
    "rowId": 4077,
    "orderId": "CA-2015-100685",
    "orderDate": "12/19/15",
    "shipDate": "12/21/15",
    "shipMode": "Second Class",
    "customerId": "SM-20950",
    "customerName": "Suzanne McNair",
    "segment": "Corporate",
    "country": "United States",
    "city": "Omaha",
    "state": "Nebraska",
    "postalCode": 68104,
    "region": "Central",
    "productId": "OFF-BI-10003094",
    "category": "Office Supplies",
    "subCategory": "Binders",
    "productName": "Self-Adhesive Ring Binder Labels",
    "sales": 7.04,
    "quantity": 2,
    "discount": 0,
    "profit": 3.3088
  },
  {
    "rowId": 4078,
    "orderId": "CA-2015-100685",
    "orderDate": "12/19/15",
    "shipDate": "12/21/15",
    "shipMode": "Second Class",
    "customerId": "SM-20950",
    "customerName": "Suzanne McNair",
    "segment": "Corporate",
    "country": "United States",
    "city": "Omaha",
    "state": "Nebraska",
    "postalCode": 68104,
    "region": "Central",
    "productId": "OFF-FA-10003472",
    "category": "Office Supplies",
    "subCategory": "Fasteners",
    "productName": "Bagged Rubber Bands",
    "sales": 5.04,
    "quantity": 4,
    "discount": 0,
    "profit": 0.2016
  },
  {
    "rowId": 4079,
    "orderId": "CA-2015-100685",
    "orderDate": "12/19/15",
    "shipDate": "12/21/15",
    "shipMode": "Second Class",
    "customerId": "SM-20950",
    "customerName": "Suzanne McNair",
    "segment": "Corporate",
    "country": "United States",
    "city": "Omaha",
    "state": "Nebraska",
    "postalCode": 68104,
    "region": "Central",
    "productId": "OFF-PA-10001289",
    "category": "Office Supplies",
    "subCategory": "Paper",
    "productName": "White Computer Printout Paper by Universal",
    "sales": 116.28,
    "quantity": 3,
    "discount": 0,
    "profit": 56.9772
  },
  {
    "rowId": 4104,
    "orderId": "CA-2017-137456",
    "orderDate": "12/21/17",
    "shipDate": "12/21/17",
    "shipMode": "Same Day",
    "customerId": "RB-19465",
    "customerName": "Rick Bensley",
    "segment": "Home Office",
    "country": "United States",
    "city": "Fremont",
    "state": "Nebraska",
    "postalCode": 68025,
    "region": "Central",
    "productId": "FUR-FU-10001940",
    "category": "Furniture",
    "subCategory": "Furnishings",
    "productName": "Staple-based wall hangings",
    "sales": 15.92,
    "quantity": 2,
    "discount": 0,
    "profit": 7.0048
  }
];

export default Nebraska;
